name: Create Release

on:
  workflow_dispatch:

env:
  flutter-version: "3.41.3"

jobs:
  build_android:
    name: Build and Release Android
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          cache: true

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build APK
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PW: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          mkdir -p android/app
          
          if [ -n "$KEYSTORE_B64" ]; then
            echo "Secrets found! Building Signed Release..."
            
            # Decode keystore
            echo "$KEYSTORE_B64" | tr -d '\n ' | base64 --decode > android/app/upload-keystore.jks
            
            # Create key.properties using printf to avoid YAML indentation errors
            printf "storeFile=upload-keystore.jks\nstorePassword=$KEYSTORE_PW\nkeyPassword=$KEYSTORE_PW\nkeyAlias=upload\n" > android/key.properties
            
            flutter build apk --release --split-per-abi
          else
            echo "No secrets found. Creating dummy key.properties for Gradle..."
            
            # Dummy file to prevent the 'null cannot be cast to String' error
            printf "storeFile=debug.keystore\nstorePassword=android\nkeyPassword=android\nkeyAlias=androiddebugkey\n" > android/key.properties
            
            flutter build apk --debug
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.APP_VERSION }}
          name: v${{ env.APP_VERSION }}
          generate_release_notes: true
          files: build/app/outputs/flutter-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
